//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA4_KYRS_DEMO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Event
    {
        public int IDActivity { get; set; }
        public int IDEvent { get; set; }
        public int Day { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public int IDUser_Moder { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
