//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA4_KYRS_DEMO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Type_Dictionary
    {
        public int IDEvent { get; set; }
        public int IDType { get; set; }
        public int IDDictionary { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Event Event { get; set; }
        public virtual TypeofEvent TypeofEvent { get; set; }
    }
}
