//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA4_KYRS_DEMO.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Praktika2222Entities : DbContext
    {
        private static Praktika2222Entities _context;
        public Praktika2222Entities()
            : base("name=Praktika2222Entities")
        {
        }
        public static Praktika2222Entities Getcontext()
        {
            if (_context == null)
                _context = new Praktika2222Entities();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Activity_Event> Activity_Event { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Event_Activity_Jury> Event_Activity_Jury { get; set; }
        public virtual DbSet<Event_Type_Dictionary> Event_Type_Dictionary { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<TypeofEvent> TypeofEvent { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
